{% set name = "onnxmltools" %}
{% set version = "1.11.2" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/onnx/onnxmltools/archive/v{{ version }}.tar.gz
  sha256: 0db032ac4625e35da757465d6f01bc3f4ce3d6e112d7f50c1a57c8816695eec4

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  string: pyh{{ PKG_HASH }}_pb{{ protobuf | replace(".*", "")}}_{{ PKG_BUILDNUM }}

requirements:
  host:
    - pip
    - python
  run:
    - python
    - numpy {{ numpy }}
    - onnx {{ onnx }}
    - skl2onnx
    - onnxruntime

test:
  imports:
    - onnxmltools

about:
  home: https://github.com/onnx/onnxmltools
  summary: ONNXMLTools enables conversion of models to ONNX
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - open-ce/open-ce-dev-team
