{% set name = "onnxmltools" %}
{% set version = "1.11.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/onnx/onnxmltools/archive/{{ version }}.tar.gz
  sha256: 6c703a3dd78c4bb4bfaf4b2ca75602a53d455b11215a0656b166405d75066b8d

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  string: pyh{{ PKG_HASH }}_pb{{ protobuf | replace(".*", "")}}_{{ PKG_BUILDNUM }}

requirements:
  host:
    - pip
    - python
  run:
    - python
    - numpy {{ numpy }}
    - onnx {{ onnx }}
    - skl2onnx

test:
  imports:
    - onnxmltools

about:
  home: https://github.com/onnx/onnxmltools
  summary: ONNXMLTools enables conversion of models to ONNX
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - open-ce/open-ce-dev-team
